name: paisa_pani_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  intl: ^0.18.1 # Use a stable version
  another_telephony: ^0.4.1
  permission_handler: ^11.0.1 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # --- FIXES ---
  fl_chart: ^0.68.0        # Updated to fix the build error
  path_provider: ^2.1.3    # Updated to a recent version
  http: ^1.2.1             # Updated to a recent version
  # --- END FIXES ---

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  hive_generator: ^2.0.1
  build_runner: ^2.4.8 
  
  flutter_lints: ^3.0.0 # Corrected to a valid version

flutter:
  uses-material-design: true
  